repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --tf-init-args=-upgrade
          - --tf-init-args=-backend=false
      - id: terraform_docs
        args:
          - --args=--lockfile=false
          - --args=--config=.terraform-docs.yaml
      - id: terraform_tflint
        args:
          - --args=--recursive
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: detect-aws-credentials
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.json$
