#cloud-config
write_files:
  - path: /etc/cloud/cloud.cfg.d/99_preserve_hostname.cfg
    owner: root:root
    permissions: "0644"
    content: "preserve_hostname: true"

runcmd:
  - sed -i -E "s?^(#|)Port .*?Port ${ssh_port}?" /etc/ssh/sshd_config
  - systemctl restart sshd
  - setenforce 0
  - sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
